// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gosupervisor.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProcessStatus_Status int32

const (
	ProcessStatus_INIT     ProcessStatus_Status = 0
	ProcessStatus_STARTING ProcessStatus_Status = 1
	ProcessStatus_RUNNING  ProcessStatus_Status = 2
	ProcessStatus_STOPED   ProcessStatus_Status = 4
	ProcessStatus_FAILED   ProcessStatus_Status = 5
)

var ProcessStatus_Status_name = map[int32]string{
	0: "INIT",
	1: "STARTING",
	2: "RUNNING",
	4: "STOPED",
	5: "FAILED",
}

var ProcessStatus_Status_value = map[string]int32{
	"INIT":     0,
	"STARTING": 1,
	"RUNNING":  2,
	"STOPED":   4,
	"FAILED":   5,
}

func (x ProcessStatus_Status) String() string {
	return proto.EnumName(ProcessStatus_Status_name, int32(x))
}

func (ProcessStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{3, 0}
}

type CommandRequest_Command int32

const (
	CommandRequest_NONE    CommandRequest_Command = 0
	CommandRequest_STOP    CommandRequest_Command = 1
	CommandRequest_START   CommandRequest_Command = 2
	CommandRequest_RESTART CommandRequest_Command = 3
	CommandRequest_KILL    CommandRequest_Command = 4
)

var CommandRequest_Command_name = map[int32]string{
	0: "NONE",
	1: "STOP",
	2: "START",
	3: "RESTART",
	4: "KILL",
}

var CommandRequest_Command_value = map[string]int32{
	"NONE":    0,
	"STOP":    1,
	"START":   2,
	"RESTART": 3,
	"KILL":    4,
}

func (x CommandRequest_Command) String() string {
	return proto.EnumName(CommandRequest_Command_name, int32(x))
}

func (CommandRequest_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{7, 0}
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	ServiceVersion       string   `protobuf:"bytes,1,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{1}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetServiceVersion() string {
	if m != nil {
		return m.ServiceVersion
	}
	return ""
}

type ProcessSpec struct {
	ProcessName          string   `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Directory            string   `protobuf:"bytes,13,opt,name=directory,proto3" json:"directory,omitempty"`
	Environment          []string `protobuf:"bytes,12,rep,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessSpec) Reset()         { *m = ProcessSpec{} }
func (m *ProcessSpec) String() string { return proto.CompactTextString(m) }
func (*ProcessSpec) ProtoMessage()    {}
func (*ProcessSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{2}
}

func (m *ProcessSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessSpec.Unmarshal(m, b)
}
func (m *ProcessSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessSpec.Marshal(b, m, deterministic)
}
func (m *ProcessSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessSpec.Merge(m, src)
}
func (m *ProcessSpec) XXX_Size() int {
	return xxx_messageInfo_ProcessSpec.Size(m)
}
func (m *ProcessSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessSpec proto.InternalMessageInfo

func (m *ProcessSpec) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *ProcessSpec) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ProcessSpec) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ProcessSpec) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *ProcessSpec) GetEnvironment() []string {
	if m != nil {
		return m.Environment
	}
	return nil
}

type ProcessStatus struct {
	RestartedCount       int32                `protobuf:"varint,1,opt,name=restarted_count,json=restartedCount,proto3" json:"restarted_count,omitempty"`
	LastStartedTime      int32                `protobuf:"varint,2,opt,name=last_started_time,json=lastStartedTime,proto3" json:"last_started_time,omitempty"`
	Pid                  int32                `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	MemoryUsage          int32                `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	Status               ProcessStatus_Status `protobuf:"varint,5,opt,name=status,proto3,enum=ProcessStatus_Status" json:"status,omitempty"`
	Desc                 string               `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	IsManualStop         bool                 `protobuf:"varint,7,opt,name=is_manual_stop,json=isManualStop,proto3" json:"is_manual_stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProcessStatus) Reset()         { *m = ProcessStatus{} }
func (m *ProcessStatus) String() string { return proto.CompactTextString(m) }
func (*ProcessStatus) ProtoMessage()    {}
func (*ProcessStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{3}
}

func (m *ProcessStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessStatus.Unmarshal(m, b)
}
func (m *ProcessStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessStatus.Marshal(b, m, deterministic)
}
func (m *ProcessStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessStatus.Merge(m, src)
}
func (m *ProcessStatus) XXX_Size() int {
	return xxx_messageInfo_ProcessStatus.Size(m)
}
func (m *ProcessStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessStatus proto.InternalMessageInfo

func (m *ProcessStatus) GetRestartedCount() int32 {
	if m != nil {
		return m.RestartedCount
	}
	return 0
}

func (m *ProcessStatus) GetLastStartedTime() int32 {
	if m != nil {
		return m.LastStartedTime
	}
	return 0
}

func (m *ProcessStatus) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ProcessStatus) GetMemoryUsage() int32 {
	if m != nil {
		return m.MemoryUsage
	}
	return 0
}

func (m *ProcessStatus) GetStatus() ProcessStatus_Status {
	if m != nil {
		return m.Status
	}
	return ProcessStatus_INIT
}

func (m *ProcessStatus) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ProcessStatus) GetIsManualStop() bool {
	if m != nil {
		return m.IsManualStop
	}
	return false
}

type Process struct {
	Spec                 *ProcessSpec   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *ProcessStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{4}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetSpec() *ProcessSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Process) GetStatus() *ProcessStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{5}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListReply struct {
	Process              []*Process `protobuf:"bytes,1,rep,name=process,proto3" json:"process,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{6}
}

func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (m *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(m, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetProcess() []*Process {
	if m != nil {
		return m.Process
	}
	return nil
}

type CommandRequest struct {
	Command              CommandRequest_Command `protobuf:"varint,1,opt,name=command,proto3,enum=CommandRequest_Command" json:"command,omitempty"`
	ProcessName          string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{7}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetCommand() CommandRequest_Command {
	if m != nil {
		return m.Command
	}
	return CommandRequest_NONE
}

func (m *CommandRequest) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

type CommandReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandReply) Reset()         { *m = CommandReply{} }
func (m *CommandReply) String() string { return proto.CompactTextString(m) }
func (*CommandReply) ProtoMessage()    {}
func (*CommandReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{8}
}

func (m *CommandReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandReply.Unmarshal(m, b)
}
func (m *CommandReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandReply.Marshal(b, m, deterministic)
}
func (m *CommandReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandReply.Merge(m, src)
}
func (m *CommandReply) XXX_Size() int {
	return xxx_messageInfo_CommandReply.Size(m)
}
func (m *CommandReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandReply.DiscardUnknown(m)
}

var xxx_messageInfo_CommandReply proto.InternalMessageInfo

type ConfigFile struct {
	Version              string         `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Process              []*ProcessSpec `protobuf:"bytes,2,rep,name=process,proto3" json:"process,omitempty"`
	RpcAddr              string         `protobuf:"bytes,3,opt,name=rpc_addr,json=rpcAddr,proto3" json:"rpc_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigFile) Reset()         { *m = ConfigFile{} }
func (m *ConfigFile) String() string { return proto.CompactTextString(m) }
func (*ConfigFile) ProtoMessage()    {}
func (*ConfigFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd7b16f4d6554, []int{9}
}

func (m *ConfigFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFile.Unmarshal(m, b)
}
func (m *ConfigFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFile.Marshal(b, m, deterministic)
}
func (m *ConfigFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFile.Merge(m, src)
}
func (m *ConfigFile) XXX_Size() int {
	return xxx_messageInfo_ConfigFile.Size(m)
}
func (m *ConfigFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFile.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFile proto.InternalMessageInfo

func (m *ConfigFile) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConfigFile) GetProcess() []*ProcessSpec {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ConfigFile) GetRpcAddr() string {
	if m != nil {
		return m.RpcAddr
	}
	return ""
}

func init() {
	proto.RegisterEnum("ProcessStatus_Status", ProcessStatus_Status_name, ProcessStatus_Status_value)
	proto.RegisterEnum("CommandRequest_Command", CommandRequest_Command_name, CommandRequest_Command_value)
	proto.RegisterType((*PingRequest)(nil), "PingRequest")
	proto.RegisterType((*PingReply)(nil), "PingReply")
	proto.RegisterType((*ProcessSpec)(nil), "ProcessSpec")
	proto.RegisterType((*ProcessStatus)(nil), "ProcessStatus")
	proto.RegisterType((*Process)(nil), "Process")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListReply)(nil), "ListReply")
	proto.RegisterType((*CommandRequest)(nil), "CommandRequest")
	proto.RegisterType((*CommandReply)(nil), "CommandReply")
	proto.RegisterType((*ConfigFile)(nil), "ConfigFile")
}

func init() { proto.RegisterFile("gosupervisor.proto", fileDescriptor_993bd7b16f4d6554) }

var fileDescriptor_993bd7b16f4d6554 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x8d, 0x1d, 0xe7, 0xdf, 0xd8, 0x49, 0xfd, 0x5b, 0xe9, 0x27, 0x4c, 0xc5, 0x21, 0xac, 0x50,
	0x89, 0x40, 0x18, 0x11, 0xb8, 0xa3, 0xd2, 0xa6, 0x55, 0x44, 0x48, 0x2b, 0x27, 0xe5, 0xc0, 0xc5,
	0x72, 0xed, 0x25, 0x5a, 0x29, 0xf6, 0x9a, 0xdd, 0x75, 0xa5, 0x9c, 0xf9, 0x1e, 0x5c, 0xf9, 0x2c,
	0x7c, 0x2b, 0xb4, 0xeb, 0x3f, 0x49, 0xca, 0x29, 0x33, 0x6f, 0xc6, 0x9b, 0x37, 0x6f, 0xdf, 0x0e,
	0xa0, 0x0d, 0x13, 0x45, 0x4e, 0xf8, 0x03, 0x15, 0x8c, 0xfb, 0x39, 0x67, 0x92, 0xe1, 0x21, 0xd8,
	0xb7, 0x34, 0xdb, 0x04, 0xe4, 0x47, 0x41, 0x84, 0xc4, 0x1f, 0x60, 0x50, 0xa6, 0xf9, 0x76, 0x87,
	0x5e, 0xc2, 0x89, 0x50, 0xdd, 0x31, 0x09, 0x1f, 0x08, 0x17, 0x94, 0x65, 0x9e, 0x31, 0x36, 0x26,
	0x83, 0x60, 0x54, 0xc1, 0x5f, 0x4b, 0x14, 0xff, 0x32, 0xc0, 0xbe, 0xe5, 0x2c, 0x26, 0x42, 0xac,
	0x72, 0x12, 0xa3, 0xe7, 0xe0, 0xe4, 0x65, 0x1a, 0x66, 0x51, 0x4a, 0xaa, 0xaf, 0xec, 0x0a, 0x5b,
	0x46, 0x29, 0x41, 0x1e, 0xf4, 0x62, 0x96, 0xa6, 0x51, 0x96, 0x78, 0xa6, 0xae, 0xd6, 0x29, 0x42,
	0x60, 0x15, 0x82, 0x70, 0xaf, 0xad, 0x61, 0x1d, 0xa3, 0x67, 0x30, 0x48, 0x28, 0x27, 0xb1, 0x64,
	0x7c, 0xe7, 0x0d, 0x75, 0x61, 0x0f, 0xa0, 0x31, 0xd8, 0x24, 0x7b, 0xa0, 0x9c, 0x65, 0x29, 0xc9,
	0xa4, 0xe7, 0x8c, 0xdb, 0xea, 0xdf, 0x0e, 0x20, 0xfc, 0xc7, 0x84, 0x61, 0x4d, 0x50, 0x46, 0xb2,
	0x10, 0x6a, 0x36, 0x4e, 0x84, 0x8c, 0xb8, 0x24, 0x49, 0x18, 0xb3, 0x22, 0x93, 0x9a, 0x65, 0x27,
	0x18, 0x35, 0xf0, 0x85, 0x42, 0xd1, 0x2b, 0xf8, 0x6f, 0x1b, 0x09, 0x19, 0xd6, 0xbd, 0x92, 0xa6,
	0x44, 0x53, 0xee, 0x04, 0x27, 0xaa, 0xb0, 0x2a, 0xf1, 0x35, 0x4d, 0x09, 0x72, 0xa1, 0x9d, 0xd3,
	0x44, 0x33, 0xef, 0x04, 0x2a, 0x54, 0x4a, 0xa4, 0x24, 0x65, 0x7c, 0x17, 0x16, 0x22, 0xda, 0x10,
	0xcf, 0xd2, 0x25, 0xbb, 0xc4, 0xee, 0x14, 0x84, 0xde, 0x40, 0x57, 0x68, 0x4e, 0x5e, 0x67, 0x6c,
	0x4c, 0x46, 0xd3, 0xff, 0xfd, 0x23, 0xa6, 0x7e, 0xf9, 0x13, 0x54, 0x4d, 0x4a, 0x9e, 0x84, 0x88,
	0xd8, 0xeb, 0x96, 0xf2, 0xa8, 0x18, 0xbd, 0x80, 0x11, 0x15, 0x61, 0x1a, 0x65, 0x45, 0xb4, 0x0d,
	0x85, 0x64, 0xb9, 0xd7, 0x1b, 0x1b, 0x93, 0x7e, 0xe0, 0x50, 0xf1, 0x45, 0x83, 0x2b, 0xc9, 0x72,
	0x3c, 0x83, 0x6e, 0x35, 0x7c, 0x1f, 0xac, 0xf9, 0x72, 0xbe, 0x76, 0x5b, 0xc8, 0x81, 0xfe, 0x6a,
	0x7d, 0x1e, 0xac, 0xe7, 0xcb, 0x6b, 0xd7, 0x40, 0x36, 0xf4, 0x82, 0xbb, 0xe5, 0x52, 0x25, 0x26,
	0x02, 0xe8, 0xae, 0xd6, 0x37, 0xb7, 0xb3, 0x4b, 0xd7, 0x52, 0xf1, 0xd5, 0xf9, 0x7c, 0x31, 0xbb,
	0x74, 0x3b, 0x78, 0x05, 0xbd, 0x8a, 0x20, 0x1a, 0x83, 0x25, 0x72, 0x12, 0x6b, 0xe5, 0xec, 0xa9,
	0xe3, 0x1f, 0x78, 0x20, 0xd0, 0x15, 0x74, 0xd6, 0x0c, 0x67, 0xea, 0x9e, 0xd1, 0xf1, 0x70, 0xf5,
	0x54, 0xca, 0x86, 0x0b, 0x2a, 0x64, 0x6d, 0xc3, 0xb7, 0x30, 0x28, 0x53, 0x65, 0x43, 0x0c, 0xbd,
	0xca, 0x39, 0x9e, 0x31, 0x6e, 0x4f, 0xec, 0x69, 0xbf, 0x3e, 0x24, 0xa8, 0x0b, 0xf8, 0xb7, 0x01,
	0xa3, 0x8b, 0xd2, 0x40, 0xd5, 0x19, 0xe8, 0xdd, 0xde, 0x61, 0x86, 0x16, 0xf6, 0x89, 0x7f, 0xdc,
	0xd1, 0xa4, 0x8d, 0xf5, 0x1e, 0xfb, 0xd6, 0xfc, 0xc7, 0xb7, 0xf8, 0x23, 0xf4, 0xaa, 0xcf, 0x94,
	0x8a, 0xcb, 0x9b, 0xe5, 0xcc, 0x6d, 0xa9, 0x48, 0x49, 0xe5, 0x1a, 0x68, 0x00, 0x1d, 0xad, 0xa7,
	0x6b, 0x6a, 0x31, 0x67, 0x65, 0xd2, 0x56, 0x1d, 0x9f, 0xe7, 0x8b, 0x85, 0x6b, 0xe1, 0x11, 0x38,
	0x0d, 0x8d, 0x7c, 0xbb, 0xc3, 0x14, 0xe0, 0x82, 0x65, 0xdf, 0xe9, 0xe6, 0x8a, 0x6e, 0xf5, 0xb3,
	0x38, 0x7e, 0x6a, 0x75, 0x8a, 0xce, 0xf6, 0x2a, 0x98, 0x5a, 0x85, 0x63, 0xb9, 0xeb, 0x22, 0x7a,
	0x0a, 0x7d, 0x9e, 0xc7, 0x61, 0x94, 0x24, 0xf5, 0x13, 0xea, 0xf1, 0x3c, 0x3e, 0x4f, 0x12, 0x3e,
	0xfd, 0x69, 0x80, 0x73, 0xcd, 0x56, 0xcd, 0x0a, 0x40, 0x18, 0x2c, 0xf5, 0xda, 0x91, 0xe3, 0x1f,
	0xec, 0x80, 0x53, 0xf0, 0x9b, 0x15, 0x80, 0x5b, 0xaa, 0x47, 0x5d, 0x05, 0x72, 0xfc, 0x83, 0x0b,
	0x3a, 0x05, 0xbf, 0xb9, 0x1f, 0xdc, 0x42, 0xaf, 0xf7, 0xa2, 0x9c, 0x3c, 0x12, 0xf9, 0x74, 0xe8,
	0x1f, 0x8d, 0xdb, 0xfa, 0x64, 0x7d, 0x33, 0xf3, 0xfb, 0xfb, 0xae, 0x5e, 0x3f, 0xef, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xc5, 0xb9, 0x5b, 0x33, 0x94, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoSupervisorClient is the client API for GoSupervisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoSupervisorClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandReply, error)
}

type goSupervisorClient struct {
	cc *grpc.ClientConn
}

func NewGoSupervisorClient(cc *grpc.ClientConn) GoSupervisorClient {
	return &goSupervisorClient{cc}
}

func (c *goSupervisorClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/GoSupervisor/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSupervisorClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/GoSupervisor/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSupervisorClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/GoSupervisor/Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoSupervisorServer is the server API for GoSupervisor service.
type GoSupervisorServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
	Command(context.Context, *CommandRequest) (*CommandReply, error)
}

// UnimplementedGoSupervisorServer can be embedded to have forward compatible implementations.
type UnimplementedGoSupervisorServer struct {
}

func (*UnimplementedGoSupervisorServer) Ping(ctx context.Context, req *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedGoSupervisorServer) List(ctx context.Context, req *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedGoSupervisorServer) Command(ctx context.Context, req *CommandRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}

func RegisterGoSupervisorServer(s *grpc.Server, srv GoSupervisorServer) {
	s.RegisterService(&_GoSupervisor_serviceDesc, srv)
}

func _GoSupervisor_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSupervisorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoSupervisor/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSupervisorServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSupervisor_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSupervisorServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoSupervisor/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSupervisorServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSupervisor_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSupervisorServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoSupervisor/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSupervisorServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoSupervisor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GoSupervisor",
	HandlerType: (*GoSupervisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GoSupervisor_Ping_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GoSupervisor_List_Handler,
		},
		{
			MethodName: "Command",
			Handler:    _GoSupervisor_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gosupervisor.proto",
}
